# Set all versions
CUSTOM_BUILD_TYPE ?= UNOFFICIAL
CUSTOM_BUILD_DATE := $(shell date -u +%Y%m%d)
CUSTOM_PLATFORM_VERSION := 9.0

TARGET_PRODUCT_SHORT := $(subst ctosp_,,$(CUSTOM_BUILD))
CTOSP_MAINTAINER ?= $(USER)

ifeq ($(IS_GO_VERSION), true)
CUSTOM_VERSION := CTOSP_go_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
ROM_FINGERPRINT := CTOSP_go/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)
else
CUSTOM_VERSION := CTOSP_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
ROM_FINGERPRINT := CTOSP/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)
endif

CUSTOM_PROPERTIES := \
    org.ctosp.version=$(CUSTOM_VERSION) \
    org.ctosp.build_date=$(CUSTOM_BUILD_DATE) \
    org.ctosp.build_type=$(CUSTOM_BUILD_TYPE) \
    org.ctosp.fingerprint=$(ROM_FINGERPRINT) \
    org.ctosp.device=$(CUSTOM_BUILD) \
    org.ctosp.maintainer=$(CTOSP_MAINTAINER)
